use infsci2710;
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (1,"Inspiron 15","220","249.99","home","laptop","Inspiron","jpg/1.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (2,"Inspiron 11 3000 2-in-1","350","399.99","home","laptop","Inspiron","jpg/2.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (3,"Inspiron 15 3000","340","379.99","home","laptop","Inspiron","jpg/3.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (4,"Inspiron 14 5000","490","599.99","home","laptop","Inspiron","jpg/4.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (5,"Inspiron 15 5000","570","649.99","home","laptop","Inspiron","jpg/5.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (6,"Inspiron 17 5000","400","449.99","home","laptop","Inspiron","jpg/6.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (7,"Inspiron 13 7000","530","599.99","home","laptop","Inspiron","jpg/7.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (8,"Inspiron 14 7000","600","649.99","home","laptop","Inspiron","jpg/8.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (9,"Inspiron 15 7000","650","749.99","home","laptop","Inspiron","jpg/9.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (10,"Inspiron 17 7000","730","849.99","home","laptop","Inspiron","jpg/10.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (11,"XPS 12 2-in-1","840","1099.99","home","laptop","XPS","jpg/1.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (12,"XPS 13","960","1199.99","home","laptop","XPS","jpg/12.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (13,"XPS 15","1200","1549","home","laptop","XPS","jpg/13.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (14,"Alienware 13","870","999.99","home","laptop","Alienware","jpg/14.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (15,"Alienware 17","1280","1399.99","home","laptop","Alienware","jpg/15.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (16,"Alienware 18","1600","2099.99","home","laptop","Alienware","jpg/16.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (17,"Chromebook 11","249","279.99","home","laptop","Chromebook","jpg/17.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (18,"Small Desktop 3000 Series","200","229.99","home","PC","Inspiron","jpg/18.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (19,"Desktop 3000 Series","430","479.99","home","PC","Inspiron","jpg/19.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (20,"20\" All-in-One 3000 Series","280","329.99","home","PC","Inspiron","jpg/20.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (21,"20\" All-in-One 3000 Series","460","529.99","home","PC","Inspiron","jpg/21.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (22,"23\’ All-in-One 5000 Series","500","599.99","home","PC","Inspiron","jpg/22.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (23,"23\" All-in-One 7000 Series","840","949.99","home","PC","Inspiron","jpg/23.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (24,"8700","560","599.99","home","PC","XPS","jpg/24.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (25,"8700 Special Edition","1050","1299.99","home","PC","XPS","jpg/25.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (26,"18\" All-in-One","680","749","home","PC","XPS","jpg/26.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (27,"27\' All-in-On e","1200","1599","home","PC","XPS","jpg/27.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (28,"Alienware Alpha","520","549.99","home","PC","Alienware","jpg/28.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (29,"Alienware X51","600","649.99","home","PC","Alienware","jpg/29.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (30,"Alienware Area-51","1300","1699.99","home","PC","Alienware","jpg/30.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (31,"Chromebox","170","179.99","home","PC","Chromebox","jpg/31.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (32,"Latitude 3000","450","499.99","work","laptop","Latitude","jpg/32.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (33,"Latitude 5000","650","749.99","work","laptop","Latitude","jpg/33.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (34,"Latitude 7000","900","1199.99","work","laptop","Latitude","jpg/34.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (35,"Latitude 6","800","1049.99","work","laptop","Latitude","jpg/35.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (36,"Precision Tower Workstations","650","689.99","work","laptop","Precision","jpg/36.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (37,"Precision Mobile Workstations","900","999.99","work","laptop","Precision","jpg/37.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (38,"Precision Rack","1600","2209.99","work","laptop","Precision","jpg/38.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (39,"Inspiron 3000","300","399.99","work","laptop","Inspiron","jpg/39.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (40,"Inspiron 5000","500","649.99","work","laptop","Inspiron","jpg/40.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (41,"Inspiron 7000","630","749.99","work","laptop","Inspiron","jpg/41.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (42,"Chromebook 11","160","279.99","work","laptop","Chromebook","jpg/42.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (43,"XPS 12","900","1099.99","work","laptop","XPS","jpg/43.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (44,"XPS 13","1000","1199.99","work","laptop","XPS","jpg/44.jpg");
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (45,"XPS 15","1100","1199.99","work","laptop","XPS","jpg/45.jpg");
 INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (46,"OptiPlex 3020","360","399","work","PC","OptiPlex",'jpg/46.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (47,"New OptiPlex 7020","560","649","work","PC","OptiPlex",'jpg/47.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (48,"OptiPlex 7010","660","729","work","PC","OptiPlex",'jpg/48.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (49,"OptiPlex 9020","630","699","work","PC","OptiPlex",'jpg/49.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (50,"OptiPlex All-in-Ones","700","789","work","PC","OptiPlex",'jpg/50.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (51,"OptiPlex XE2","1270","1343.99","work","PC","OptiPlex",'jpg/51.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (52,"Precision Tower Workstations","600","689","work","PC","Precision",'jpg/52.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (53,"Precision Mobile Workstations","890","999","work","PC","Precision",'jpg/53.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (54,"Precision Rack Workstations","1700","2239","work","PC","Precision",'jpg/54.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (55,"Inspiron Budget friendly","220","249.99","work","PC","Inspiron",'jpg/55.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (56,"InspironAll-in-One","480","539.99","work","PC","Inspiron",'jpg/56.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (57,"XPS For the Ultimate experience","600","669.99","work","PC","XPS",'jpg/57.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (58,"Chrombox","130","179.99","work","PC","Chrombox",'jpg/58.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (59,"keyboard","30","50","home","accessory","Chrombox",'jpg/59.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (60,"mouse","15","20","home","accessory","Chrombox",'jpg/60.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (61,"wireless keyboard","50","80","home","accessory","Chrombox",'jpg/61.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (62,"adapter","15","20","home","accessory","Chrombox",'jpg/62.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (63,"battery","30","50","home","accessory","Chrombox",'jpg/63.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (64,"laptop bag","40","70","work","accessory","Chrombox",'jpg/64.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (65,"messenger bag","30","60","work","accessory","Chrombox",'jpg/65.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (66,"speaker","20","30","work","accessory","Chrombox",'jpg/66.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (67,"headphone","40","55","work","accessory","Chrombox",'jpg/67.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (68,"earbud","55","80","work","accessory","Chrombox",'jpg/68.jpg');
INSERT INTO product (productID,name,unitCost,referenceUnitPrice,productType,category,series,imageFileName) VALUES (69,"headset","60","90","work","accessory","Chrombox",'jpg/69.jpg');