use infsci2710;
INSERT INTO login (employeeID,password,userType) VALUES (1,'qyrkslb825','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (2,'izrwwbu221','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (3,'osriouk749','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (4,'hpsteqz436','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (5,'forywrv607','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (6,'hzfmspj555','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (7,'afrgwfy411','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (8,'nglzewt742','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (9,'ealrdof046','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (10,'nncateb894','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (11,'bdluzsg820','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (12,'stjnnil421','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (13,'fywtgno466','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (14,'epkyvqr434','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (15,'zzbokkc420','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (16,'exypdqv630','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (17,'nrlvvvr317','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (18,'wdarhqy397','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (19,'dgwcrug624','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (20,'lsftanv413','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (21,'txqsfjy263','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (22,'owxgvih608','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (23,'erlqong376','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (24,'pfqlqvz319','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (25,'xurkcrs475','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (26,'xhczwxp557','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (27,'nftcqsj342','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (28,'cnwyfez414','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (29,'llwnunk656','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (30,'dzbshva392','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (31,'cymctmv879','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (32,'sohsjzu721','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (33,'tryjvrg027','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (34,'xkadivd850','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (35,'akgbmeu859','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (36,'odqazff464','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (37,'kpqrwee560','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (38,'gidsaoa247','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (39,'itrkzpi079','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (40,'defpevp214','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (41,'xemfooh655','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (42,'spebqdp328','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (43,'cpocjyg500','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (44,'ynhdvai989','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (45,'qrwjhpp495','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (46,'utygztl870','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (47,'jcvfggb774','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (48,'tndblsz095','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (49,'eemfrzm577','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (50,'zsjnomu518','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (51,'ndsterf374','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (52,'cmmbajh748','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (53,'qpizlse022','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (54,'thfxkkl764','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (55,'odhabbl024','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (56,'luylgwf879','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (57,'pihrgdv080','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (58,'vqncyaf288','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (59,'ocdxbbb691','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (60,'qbhszpb175','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (61,'ukanijz335','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (62,'bydxhra157','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (63,'oioefpc112','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (64,'bfqcvaa693','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (65,'ocbveuy860','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (66,'objdais638','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (67,'xsjdevm765','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (68,'hpqizin367','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (69,'hljqqsg870','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (70,'rdgyiow514','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (71,'hftwceg893','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (72,'hnsbyyq737','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (73,'ifhdgio008','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (74,'sogqwir363','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (75,'hogyeua617','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (76,'bafxweu117','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (77,'cwtyerx398','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (78,'ljatoff546','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (79,'fpjksae172','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (80,'gsabmel689','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (81,'hpdzezn354','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (82,'boqechd417','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (83,'jojauas039','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (84,'acktrgb135','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (85,'gtepxkm988','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (86,'rzmfmqr435','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (87,'lpillla556','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (88,'umoccpv788','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (89,'xnzynsa339','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (90,'hyicstc402','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (91,'ztmbvjm580','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (92,'xiypjnc039','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (93,'bewrpbv535','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (94,'dcfolmq358','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (95,'pqeeoug629','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (96,'enbewlg477','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (97,'hlcfewx499','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (98,'tpmeyvv071','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (99,'kzdinra996','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (100,'glfludh820','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (101,'umqkubh442','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (102,'gblfmam269','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (103,'usggvug579','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (104,'opduhar474','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (105,'ufkolrr186','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (106,'ofpyccr792','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (107,'penjiag577','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (108,'nsyuzfm534','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (109,'mdthfbn292','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (110,'qtphvvx691','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (111,'sabojwz035','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (112,'rocputu354','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (113,'vhtagmr008','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (114,'yqyybjm091','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (115,'kfuarev394','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (116,'lpwrvnz810','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (117,'ynlfife002','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (118,'scsxakt264','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (119,'lxkqfui535','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (120,'gusmfks902','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (121,'adgaloh503','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (122,'jowmida793','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (123,'dimlrtm971','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (124,'agufrgs103','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (125,'dmulqun073','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (126,'spothrv754','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (127,'kznhulg516','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (128,'nwzopkv379','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (129,'rjcxvhx862','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (130,'cxizoro784','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (131,'qcpowak096','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (132,'okaobzf501','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (133,'nphpzky184','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (134,'pxfaqus676','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (135,'twblvan229','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (136,'kklpbsq340','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (137,'cnnkqby974','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (138,'zzdmjux547','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (139,'zvpfmwg596','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (140,'titknfv445','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (141,'ilyqabd249','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (142,'aljnagr041','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (143,'ilochyx396','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (144,'gvvdval350','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (145,'rptekck548','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (146,'hcyrczh703','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (147,'rwbpgef855','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (148,'tqyggsz685','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (149,'fiiolws912','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (150,'ngdguyb539','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (151,'zxvcuhp280','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (152,'jllmiou065','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (153,'xlgdjdp824','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (154,'xmjsmrl130','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (155,'aqowbzj222','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (156,'kdbgnft115','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (157,'eazmkuu965','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (158,'euoplde335','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (159,'hrthyhm949','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (160,'scpbyor972','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (161,'xnjhoro653','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (162,'kteccrf698','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (163,'avvatxi257','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (164,'dayrixm295','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (165,'zqrbfyq104','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (166,'rudboaa819','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (167,'odrgjye153','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (168,'egtinfp489','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (169,'punepcw549','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (170,'jojjgqm251','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (171,'abfdayl668','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (172,'totlyyp417','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (173,'yjacchf667','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (174,'nugunmm410','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (175,'goimguj369','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (176,'ppjtpqb935','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (177,'vxnbwdt997','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (178,'mxbmbwa723','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (179,'nsasomz660','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (180,'qqpawnz041','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (181,'slnrxev450','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (182,'tessmdo318','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (183,'emsmdhc324','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (184,'rkmwxoa650','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (185,'csgtksl086','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (186,'uwomrfv690','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (187,'hfiemoo483','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (188,'qwabnob214','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (189,'willpat389','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (190,'mihzrzd718','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (191,'wdwwtjr911','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (192,'cirawik197','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (193,'frmfuvv919','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (194,'rofxlou220','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (195,'myuynsz570','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (196,'yytrgac572','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (197,'lohzykh824','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (198,'aejxwqx274','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (199,'uvebqwx411','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (200,'boqeliq162','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (201,'wszkykn268','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (202,'rdhanbl321','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (203,'lqjgrzr391','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (204,'fhmdrrj957','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (205,'khetgza762','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (206,'jhkjtyd679','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (207,'ipmmhvk388','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (208,'crfdtdn794','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (209,'vdaaqre605','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (210,'xqtjmvy031','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (211,'vkorqjq034','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (212,'bwnjvgq742','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (213,'gxmgaos534','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (214,'genlsyn186','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (215,'ngffifc821','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (216,'kuapctk308','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (217,'rzunohr977','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (218,'ljblfhh525','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (219,'vmfnjnp248','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (220,'vobphjy353','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (221,'tnlpvqk824','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (222,'emxusss031','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (223,'mgpwfcr812','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (224,'xrzaxpn845','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (225,'rzfqwcm485','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (226,'vbycwwf909','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (227,'gbacfoo781','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (228,'bewtnrv123','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (229,'avdronp837','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (230,'vskkkok803','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (231,'jsdqkff313','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (232,'hrnhied803','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (233,'kncxudx835','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (234,'lejrhjh443','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (235,'mcpgdca682','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (236,'tsleoyt385','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (237,'czuyuaj442','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (238,'fbxuztr375','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (239,'xwtxshb666','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (240,'hmwpqco318','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (241,'dziytnb748','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (242,'wmdeufm956','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (243,'ukqlxki638','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (244,'bxamdbc014','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (245,'gzdhvyp582','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (246,'rmbtmna511','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (247,'emysrls444','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (248,'cnclgpx187','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (249,'xddjsxe400','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (250,'fkyltav121','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (251,'nesvnng356','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (252,'mjelfkc864','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (253,'sjbdsbg334','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (254,'nuqzlko131','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (255,'ujbmaoz276','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (256,'oepwply246','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (257,'jycbcan797','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (258,'ygxiypq666','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (259,'kyeugpp853','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (260,'gthtcde417','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (261,'tsbpsrd131','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (262,'sxlbozo216','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (263,'qqrlwke895','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (264,'wyeclyj760','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (265,'lggtutj989','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (266,'kongaec487','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (267,'stwosjn826','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (268,'hpwuxqj718','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (269,'myygpmm507','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (270,'ddjdapk125','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (271,'ublkvcm239','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (272,'rhchtnu005','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (273,'mjzoepy994','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (274,'ahaehok565','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (275,'qwojxhk720','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (276,'wqtjmgz657','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (277,'hcjmxwc093','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (278,'bhiomlq135','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (279,'fnkorxc514','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (280,'pmjfihc221','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (281,'uxgzdbp457','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (282,'lynzjwc518','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (283,'kwivzot373','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (284,'agechev260','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (285,'lapsaqf267','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (286,'urnbwoh673','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (287,'tqknhrx801','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (288,'erplszj138','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (289,'unjzota979','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (290,'wqthfoj577','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (291,'siapdxh726','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (292,'bfyjcra470','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (293,'rkzixzk334','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (294,'rguqmov545','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (295,'edbuoid895','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (296,'tqxnzjd055','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (297,'htkupen123','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (298,'snfdrcd300','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (299,'hqdbwaf858','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (300,'guzipfk229','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (301,'zgavnfn616','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (302,'cjcbggl709','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (303,'awpvxjb210','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (304,'rqfidtx232','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (305,'aabfahl533','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (306,'wdwlecj164','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (307,'babqdnt849','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (308,'cgernuo424','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (309,'oljrfxz639','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (310,'wnucaay663','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (311,'slhjksd218','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (312,'glhwpbn103','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (313,'zvojaww514','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (314,'fbwsrez560','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (315,'jwxbaka746','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (316,'cmmmdkx841','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (317,'mwajjif362','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (318,'vyjxaok210','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (319,'ewtvhac017','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (320,'kzxkrus693','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (321,'fhxjnld284','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (322,'tkkrbqt050','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (323,'kklbpzi700','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (324,'tjwalcz251','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (325,'sxjkpbc637','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (326,'sfllddb052','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (327,'wstalfb352','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (328,'bkcbvqq433','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (329,'nwcqzfo066','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (330,'ebzunia262','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (331,'hlvsgwu967','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (332,'fmmzpot892','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (333,'rmeoxbb337','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (334,'dewjyam455','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (335,'vvqkhre950','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (336,'dglzmua458','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (337,'cjnzvmn645','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (338,'fpvseym787','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (339,'gdhavbd271','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (340,'loarylh591','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (341,'rchzqtw751','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (342,'ejnodep076','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (343,'fmeolkk718','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (344,'vpljpql199','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (345,'uljiytx595','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (346,'tzhnycc039','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (347,'vlqcdue296','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (348,'yukqztr651','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (349,'zktcriu372','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (350,'ymhkhiu492','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (351,'yhzwmgh618','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (352,'guwzhqo451','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (353,'aepfxxk147','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (354,'kchpwiz815','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (355,'khzwvsn790','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (356,'ofoqzeq965','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (357,'vqjpcmf312','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (358,'xpfhwog911','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (359,'bnvxiff109','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (360,'pvmarua411','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (361,'kumrjxl048','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (362,'cvwnflo669','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (363,'rahevos902','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (364,'wlqhaoo109','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (365,'shsloph404','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (366,'rnkjbcw985','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (367,'aocsdrb958','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (368,'mzotbgm034','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (369,'tfizitl143','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (370,'qvstwwo999','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (371,'wauxtkd916','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (372,'ztwsdhs858','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (373,'xdzkkgc093','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (374,'rsmsnmk771','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (375,'vbzajsc180','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (376,'bfvkelj457','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (377,'fquqzvx760','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (378,'unrmwca438','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (379,'fcezado078','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (380,'ricrigp097','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (381,'bleazvo281','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (382,'iwdozdn032','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (383,'kezslah821','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (384,'qrvgquo360','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (385,'tlqfmsz805','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (386,'aramuni786','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (387,'gplowkp206','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (388,'hcrexgg767','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (389,'qmutmir166','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (390,'nyinift162','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (391,'myrlbqv547','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (392,'tzwvplb443','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (393,'uyhcwbr627','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (394,'pswswxk541','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (395,'knlrtup359','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (396,'xzbcwzt556','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (397,'agsllbc987','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (398,'ferczcc511','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (399,'agkoqlr666','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (400,'rfrdfso552','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (401,'gcbgzio951','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (402,'puvgofz595','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (403,'rcphfoa484','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (404,'kbfjedv104','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (405,'hzkyejs037','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (406,'yukmqon323','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (407,'psudhxn146','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (408,'mjfzvtg043','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (409,'vsjrfqh409','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (410,'ryuoowu580','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (411,'tmqkjfi325','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (412,'jjxervq817','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (413,'oddyjin760','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (414,'twmkznu447','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (415,'fnismzt955','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (416,'zfzpqvl852','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (417,'ihdzqvr798','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (418,'njuzkvh866','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (419,'menmemd882','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (420,'nrbckza746','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (421,'zxenusz002','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (422,'qjuaqmo486','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (423,'drjsogv887','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (424,'rvcsowm308','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (425,'mhdvnqx101','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (426,'lsgiwot351','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (427,'szkmdgj600','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (428,'ztstnbx866','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (429,'fspbnhl702','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (430,'tloqetq251','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (431,'horxctd748','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (432,'bkvynik608','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (433,'ijlrkxu448','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (434,'lajxasw533','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (435,'qvougev556','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (436,'pvztxvf148','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (437,'cpxkwjb954','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (438,'jottsrf371','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (439,'nwszjiq765','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (440,'vfzkips013','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (441,'ziuqaag836','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (442,'wcmkcnw381','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (443,'eebldvg852','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (444,'qpxdsqq871','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (445,'gygjcdo706','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (446,'iehwdyd820','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (447,'dicvzql803','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (448,'jymaddy005','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (449,'aatrtid326','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (450,'nartbkp477','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (451,'uxantns909','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (452,'yctsrxv670','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (453,'ishxrmy150','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (454,'fdxvscq298','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (455,'zryayqn899','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (456,'hrinisl958','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (457,'cdbsrbh441','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (458,'srntrjq004','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (459,'mzlrrye362','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (460,'tedfxol897','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (461,'urmnnhz493','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (462,'ztnavyr900','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (463,'xxrhffy334','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (464,'zsbjjiz815','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (465,'eoerkbp064','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (466,'ozpzagj517','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (467,'jsznstc075','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (468,'rqstttm658','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (469,'qmdqtxs831','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (470,'fihkrzm169','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (471,'qxxbdqz547','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (472,'otrmeum620','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (473,'lxiieso399','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (474,'qtsrnfp622','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (475,'iiaidre188','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (476,'cylpcrc492','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (477,'zgwypdf057','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (478,'bgxinwi907','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (479,'ikdrizy124','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (480,'gcewhui082','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (481,'nljrkqa704','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (482,'rtjskuk196','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (483,'oapnazn775','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (484,'yoqmiga336','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (485,'bacwkmx316','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (486,'dbsound444','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (487,'yrhdbgf834','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (488,'oubkooy366','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (489,'tlslreb165','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (490,'hghxvqi944','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (491,'cmkymdm769','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (492,'ezdwhbg818','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (493,'pwgmggo142','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (494,'ftufnbe014','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (495,'eptnbkk723','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (496,'toqyoos929','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (497,'qwhjosu865','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (498,'uhwqotw901','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (499,'ttntqef799','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (500,'ervbxya987','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (501,'fnabzeq407','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (502,'ybrwbhq860','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (503,'vybrkbp379','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (504,'zekinuq719','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (505,'uqzrsrw090','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (506,'trmavtr526','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (507,'lwxfzfw978','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (508,'vaojbfj111','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (509,'jazoica724','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (510,'fbjrpmu975','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (511,'mxhhwvz205','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (512,'dabdyib106','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (513,'mfiwxkm982','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (514,'zlwplnd543','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (515,'edcqeoa166','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (516,'kmfmpic743','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (517,'gyezhoz684','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (518,'xbrziha290','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (519,'sflibvf227','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (520,'wtdsqtq858','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (521,'vatptxu074','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (522,'ltlovxm401','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (523,'ngtveas255','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (524,'exebvwq566','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (525,'rvstjrw042','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (526,'mewkpkz727','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (527,'kmmrsty612','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (528,'agblrsc721','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (529,'jyxwxlz235','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (530,'blaqnon142','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (531,'ujsbkgl345','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (532,'uvzhhpo694','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (533,'yzturgx021','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (534,'ghjrdqz887','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (535,'qezlsjj320','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (536,'stodrvy719','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (537,'lsndrum038','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (538,'njqkdnw586','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (539,'dtxbsuj869','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (540,'bkudkqz981','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (541,'wbvutwr834','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (542,'tpeeqcj696','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (543,'bljdudq862','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (544,'jcwriem374','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (545,'chjlqug086','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (546,'aqdrtah889','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (547,'dagdgvp747','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (548,'ityiplb930','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (549,'mwegngv907','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (550,'qfypyuy538','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (551,'ydnfdnk140','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (552,'blauggd606','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (553,'yvbbvtg954','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (554,'uhotsdh544','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (555,'avljmhi779','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (556,'ayjomfg535','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (557,'mxbpjay372','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (558,'iflpvrk446','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (559,'uawpcne899','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (560,'aurfbmz386','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (561,'arvcphv310','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (562,'rhkbdel783','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (563,'pqhxkog892','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (564,'kegvsrx842','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (565,'oogfgju774','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (566,'httyqou292','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (567,'utpejoz371','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (568,'kjdgfun206','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (569,'gjphcfy288','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (570,'urkobor240','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (571,'bvcsppo354','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (572,'hxykmbj820','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (573,'kwubqgl893','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (574,'lvkcwcu649','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (575,'bqbifup862','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (576,'xlzunyo863','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (577,'xiazgqw975','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (578,'etgicus638','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (579,'xtdzbkw902','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (580,'nxvqnzi212','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (581,'vhwhduf074','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (582,'fjirkgj569','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (583,'wtluckn055','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (584,'tbzktht933','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (585,'xyevspb507','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (586,'cjqeaqi427','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (587,'jvjedmd935','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (588,'wygywhz569','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (589,'bngaiko636','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (590,'sqeicva165','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (591,'ioqylmz195','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (592,'hkoswsw931','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (593,'jgcsmqi306','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (594,'acnfgdc659','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (595,'hjshbrz629','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (596,'vsloysh649','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (597,'yxrcxob862','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (598,'vwxwife343','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (599,'vmdcamo078','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (600,'qtayjhw392','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (601,'hzlepmb052','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (602,'mqjmpjc511','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (603,'tohvsen016','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (604,'nxmammj052','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (605,'zevwgbx211','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (606,'hvyqwdf675','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (607,'tjubjry948','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (608,'zykumot080','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (609,'icvzffj998','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (610,'fakdepi504','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (611,'mrahsbx829','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (612,'zxskvqi382','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (613,'xyxbzuo601','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (614,'aflhrss991','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (615,'mwwnlcf175','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (616,'zniiubj323','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (617,'tsiukzg007','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (618,'zuhwvsa659','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (619,'chinsvw780','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (620,'lvapktw543','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (621,'aqiyvny097','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (622,'cmxjlow612','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (623,'qaccadj517','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (624,'eckyvnu768','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (625,'afhfset519','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (626,'nsxnyrc686','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (627,'qjjilsd021','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (628,'epdyrlf995','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (629,'cmkjcqc449','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (630,'jvsnrlp543','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (631,'fuiinci619','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (632,'qldslac041','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (633,'yifbyhq177','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (634,'lsabgnd347','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (635,'bawjlxc009','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (636,'rjgiolc871','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (637,'azocrwq150','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (638,'kgqcwde149','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (639,'uiyeakd827','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (640,'wizfbtw998','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (641,'qantizh665','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (642,'lywrpes136','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (643,'sztnqbd280','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (644,'oefuzrz048','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (645,'ymkrtpu158','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (646,'mbqauzh576','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (647,'mahqadk212','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (648,'kaooakt230','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (649,'musdtyl442','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (650,'irpuzsz683','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (651,'rzlbipf732','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (652,'umppgtd971','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (653,'ttnvmns768','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (654,'fdjvtab408','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (655,'buadatd943','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (656,'eqopvap224','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (657,'fgpckau560','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (658,'ubnofoe694','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (659,'slljskt294','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (660,'ihlblqr443','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (661,'smrueox140','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (662,'jlpvkbu871','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (663,'vryqnvq358','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (664,'oqdweph909','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (665,'ztwepgx599','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (666,'zltznrf905','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (667,'hhdpxqb413','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (668,'iecqjfq614','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (669,'sxdpkyo312','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (670,'gyluugb604','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (671,'hizuivl411','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (672,'izbwsgb195','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (673,'wvqgzzu821','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (674,'gtelgyi530','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (675,'kjhzsdv536','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (676,'mlhnzkm047','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (677,'ggrgawm695','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (678,'zecnflw198','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (679,'fmzcjgi042','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (680,'tqtrzss767','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (681,'pxebywu738','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (682,'xntdmlz848','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (683,'pkcnkax808','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (684,'woawcrb595','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (685,'jxaniyv684','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (686,'ykwsqgo297','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (687,'jjlhaxw938','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (688,'ybujskl859','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (689,'jegkqkk797','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (690,'upegzqy320','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (691,'hpfvott358','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (692,'mhjrxaz890','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (693,'cwxzbse855','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (694,'vfiezam282','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (695,'dtlodff362','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (696,'teagwho431','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (697,'wdvyztg051','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (698,'oevjkkq595','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (699,'kqrhxxj278','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (700,'oeqzjgk179','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (701,'owlcfwt116','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (702,'cptsydw291','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (703,'ipbciyi920','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (704,'faubxlk968','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (705,'vxpbhqs749','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (706,'lxihhzu328','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (707,'pusmdri068','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (708,'rwejzcj987','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (709,'nddfivx400','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (710,'wlghhnu039','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (711,'zqjmnkw625','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (712,'iwtmldk993','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (713,'cqnobzy022','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (714,'xtbsfzw692','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (715,'pkosrzw302','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (716,'gkpabkp059','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (717,'ntevuup458','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (718,'xuinvmz122','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (719,'ssddikp579','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (720,'vsphgfs687','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (721,'nzdkwwq369','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (722,'tzfanqi061','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (723,'vbrnbdl957','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (724,'ospzhjj579','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (725,'jjzhwer926','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (726,'meuijwh782','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (727,'reyocml129','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (728,'rvtmcil641','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (729,'jnrbyzt645','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (730,'jccasmp395','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (731,'dzlkhwr965','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (732,'voiliot805','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (733,'mupyuyh346','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (734,'gyiizih059','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (735,'pnarsmm356','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (736,'rzocnlb286','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (737,'gprywml589','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (738,'vuthwsf324','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (739,'vlzbpcv304','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (740,'xgjqnaz285','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (741,'qbgovso376','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (742,'salspfq585','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (743,'ovgqeet949','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (744,'wrlpaql013','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (745,'dtcccvs053','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (746,'zseoojm350','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (747,'hktssrq214','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (748,'ckmhcsk587','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (749,'izdbtcr539','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (750,'cmhdxke296','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (751,'lyigehg369','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (752,'qcpsnst401','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (753,'vrncpku105','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (754,'vgbuqzw366','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (755,'veclihk249','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (756,'fiwktgg612','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (757,'zkvdxbs942','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (758,'bbfuzth196','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (759,'zzuotrv527','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (760,'glhynch663','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (761,'cpbmhzd501','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (762,'gwyqgum003','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (763,'ixsymnc592','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (764,'sujtypg166','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (765,'mwsmkgn954','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (766,'pzpybti837','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (767,'ytkffpb677','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (768,'vtbbyvk437','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (769,'zbtaswx460','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (770,'dzgaxed636','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (771,'gkpzbxj150','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (772,'vimbykc643','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (773,'eoxzgbl608','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (774,'uzvdqix189','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (775,'xwygrgv130','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (776,'qucvuzb897','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (777,'jkqwhcl713','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (778,'qzgwqhv238','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (779,'vozimlo983','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (780,'yflpmrj030','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (781,'yzmugtp091','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (782,'vbaneho269','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (783,'bpfdnps375','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (784,'xnlwxxp354','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (785,'csrftvp923','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (786,'xijmszm295','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (787,'diovgfk493','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (788,'ooojldi161','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (789,'xvmscby776','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (790,'sasvfnl752','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (791,'ryleoan881','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (792,'layoery972','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (793,'kcaleoj821','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (794,'wvbvjej370','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (795,'nchwvzy388','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (796,'kvmjizk307','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (797,'olqgabk398','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (798,'tpvhwkk142','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (799,'djiedxt310','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (800,'tnyiyob358','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (801,'ogoqybb970','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (802,'lnxqftt558','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (803,'jbvavyn061','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (804,'tkhflpj971','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (805,'gguahno819','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (806,'qqvhufa022','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (807,'cxthamo848','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (808,'drrdezj555','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (809,'fqdggqr969','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (810,'uoajbqx632','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (811,'gfvqyfy108','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (812,'kmehmdi962','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (813,'krcmfjs106','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (814,'pjchmwt794','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (815,'sdgdjlw761','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (816,'krgbfqq893','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (817,'fstbqow424','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (818,'exxyygu718','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (819,'ttogaei710','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (820,'hqjviwz315','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (821,'ttsrxmg439','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (822,'ycdedcc556','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (823,'cjxweye976','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (824,'ntntwfl080','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (825,'jiwknyl723','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (826,'ljgdkgl792','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (827,'hwvegbq896','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (828,'unmjrfq548','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (829,'djjzcyi572','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (830,'eqtkgzo225','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (831,'qisdxri046','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (832,'gvavjpv088','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (833,'bwgtlhc001','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (834,'dpqudqi681','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (835,'pqyfmix192','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (836,'wqdkwan195','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (837,'lyxauwk055','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (838,'dglvnqe139','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (839,'mjnyoll025','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (840,'lhzyato082','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (841,'jvlhdug203','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (842,'sjwaqgk914','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (843,'hlyqlrp280','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (844,'lmlwppn942','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (845,'dtgdfdj001','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (846,'mdybzjy789','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (847,'nxfurif534','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (848,'pwdytty896','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (849,'gfcercb059','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (850,'zrzlbfv964','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (851,'vqveesr464','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (852,'zvyyppe359','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (853,'nyvamhy984','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (854,'mctwykt499','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (855,'khrovlr173','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (856,'dmeyxym790','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (857,'cnfgkxx816','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (858,'rjalyur511','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (859,'zogtchj907','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (860,'qilcyga343','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (861,'phpmuhh988','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (862,'zifxjqy595','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (863,'psgddmk982','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (864,'flfgolb421','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (865,'qpymzbh530','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (866,'sovsdhs686','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (867,'lezvjjk774','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (868,'jzgmqoi645','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (869,'ibiaqnm836','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (870,'dlhdfkb901','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (871,'bvcbppc101','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (872,'lcijdoy218','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (873,'pxowpdk358','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (874,'ubvexts103','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (875,'lwztpre975','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (876,'ieckzzj602','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (877,'zozbgnl571','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (878,'recskhu231','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (879,'kkmgxqj226','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (880,'oufovte764','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (881,'lwmoamm250','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (882,'zgmskjt998','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (883,'muqhzdk467','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (884,'umllsis507','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (885,'gfysbxd933','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (886,'goidyca936','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (887,'fqbphcm922','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (888,'htdrgli493','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (889,'smdgsdf458','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (890,'ktjohlw963','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (891,'ipibprm384','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (892,'xdjhztq856','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (893,'uoquwuu223','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (894,'qcnwihg500','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (895,'jvstmbm625','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (896,'dofdtei570','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (897,'qlwyktf020','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (898,'evrafkx733','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (899,'hopkyps196','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (900,'xqkuehu752','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (901,'tnjunsw019','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (902,'veevnqm036','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (903,'seucpum838','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (904,'kdypych470','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (905,'xroslxg596','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (906,'jsjryfy466','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (907,'laziljy191','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (908,'isqxbxq275','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (909,'rqzjkec992','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (910,'prndxme859','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (911,'qntxxfx043','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (912,'kqlamqw662','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (913,'ndtphqa019','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (914,'xjsiptn985','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (915,'izmfrsk815','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (916,'gdopxea509','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (917,'utlnggo693','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (918,'lrgjtuh901','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (919,'wdanvxk073','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (920,'hinvmja464','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (921,'fqkxgfo946','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (922,'bcsahwk528','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (923,'fixdojp936','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (924,'tomhipo015','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (925,'uioapvs220','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (926,'kvrbbtc040','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (927,'tcpaoss099','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (928,'lquyrjv899','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (929,'ohmvezm306','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (930,'ofhxpat564','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (931,'mfmupoz390','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (932,'fukshae217','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (933,'gtvqcxv570','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (934,'znytqno158','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (935,'yldmqgi307','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (936,'xfhbiwz796','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (937,'aytbnjz769','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (938,'gczpmik939','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (939,'nseomwe606','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (940,'mlifxtd908','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (941,'vkrtrja918','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (942,'xjvdbhv171','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (943,'hwerohy564','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (944,'xuozxcz884','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (945,'wlnsjxv782','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (946,'twpxcec856','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (947,'eqeygnv406','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (948,'xniysie300','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (949,'oeedwis273','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (950,'yfehfmj137','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (951,'emlohdc495','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (952,'ihiidyj387','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (953,'deylfum556','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (954,'yalkbmz210','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (955,'dqgdotk139','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (956,'ebawmlv632','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (957,'nscaefy499','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (958,'yckqnol787','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (959,'lxyouvm097','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (960,'kndikbh439','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (961,'fiznkmw212','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (962,'bsjlqqh938','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (963,'utlmsie923','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (964,'ppczjkk996','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (965,'wjwzwfn727','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (966,'hphpdgl672','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (967,'ywwpnxs429','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (968,'nfpqcis183','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (969,'zgejhgk422','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (970,'snoryiw607','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (971,'kbbstzt646','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (972,'xeodwqq685','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (973,'khvjqvv234','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (974,'xkiljic163','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (975,'chlhmwr019','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (976,'mbxjivz086','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (977,'lzaookg843','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (978,'mrhwywf505','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (979,'mgbptju747','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (980,'tidcwge003','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (981,'lzxynlu264','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (982,'qvivbnt427','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (983,'xxjjexx455','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (984,'rnefyom902','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (985,'clrxwvh149','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (986,'licesma629','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (987,'btaowss208','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (988,'asqwuwk463','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (989,'jkrtmhd917','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (990,'ywtzrrg406','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (991,'bvlydyp141','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (992,'wablruo554','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (993,'mzomruq363','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (994,'rhdobbv937','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (995,'mukldjk293','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (996,'tplaoay179','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (997,'wuqgqcp875','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (998,'eqvgkwk385','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (999,'mtwbmjf231','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (1000,'aytidsj215','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (1001,'qycrspm348','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1002,'hxzynsb769','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1003,'mvedhqp987','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1004,'zephzwu369','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1005,'itlazja151','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1006,'kpysivh175','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1007,'jzeoclo780','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1008,'nowcoty050','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1009,'wepuwnj829','region manager');
INSERT INTO login (employeeID,password,userType) VALUES (1010,'sgwjzzy554','region manager');
